### ISSUE TITLE
Add functions tutorial

### ISSUE THREAD

**Issue by Kunal-Garg-12** [Kunal-Garg-12/AIML-Hacktoberfest-22#5]
You are required to add a python program containing examples for python functions. Make sure to follow folder hierarchy and comment the code so beginners can understand as well. Also, add a function.md file in same folder (/Python/functions/)containing a summary on python looping.

**Comment by Kunal-Garg-12** [comment]
Sure @NyanCyanide

**Comment by subashpaul** [comment]
can i work on this project?
