### ISSUE TITLE
Add tutorial on lists in Python

### ISSUE THREAD

**Issue by Kunal-Garg-12** [Kunal-Garg-12/AIML-Hacktoberfest-22#7]
You are required to add a python program containing examples of working with list. Make sure to utilize various common methods available for python list.

Make sure to follow folder hierarchy and comment the code so beginners can understand as well. Also, add a lists.md file in same folder (/Python/lists/)containing a summary on lists and methods in python.

**Comment by ShishuSidharth** [comment]
Please assign this to me for hacktoberfest

**Comment by Kunal-Garg-12** [comment]
Assigned @ShishuSidharth
