### ISSUE TITLE
Add tutorial on Python dictionary

### ISSUE THREAD

**Issue by Kunal-Garg-12** [Kunal-Garg-12/AIML-Hacktoberfest-22#8]
You are required to add a python program containing examples of working with dictionary. Make sure to utilize various common methods available for python dictionary.

Make sure to follow folder hierarchy and comment the code so beginners can understand as well. Also, add a dictionary.md file in same folder (/Python/dictionary/)containing a summary on dictionary and methods in python.

**Comment by ShishuSidharth** [comment]
Can u please  assign this to me

**Comment by codershrutik** [comment]
Please assign this to me
