### ISSUE TITLE
Add a tutorial on OOPS in Python

### ISSUE THREAD

**Issue by Kunal-Garg-12** [Kunal-Garg-12/AIML-Hacktoberfest-22#9]
You are required to add a python program containing example of using OOPS.

Make sure to follow folder hierarchy and comment the code so beginners can understand as well. Also, add a OOPS.md file in same folder (/Python/OOPS/) containing a summary on OOPS and why is it useful in python.

**Comment by yash-sharma13** [comment]
please assign me this one

**Comment by Kunal-Garg-12** [comment]
Assigned to you @yash-sharma13
